name: Build and deploy to an VM

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Running Docker Compose
        run: docker compose up -d --build
